name: 'Follett - Where, What?'
favicon: null
layout_spectrum: 0.16113645350560546
typography_spectrum: 0.43726812209933996
title: Contact
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c4c0a7'
    - '#000000'
    - '#252935'
    - '#68645f'
  brandStrength: 0.625
  lightness: 0.6280691341962665
  saturation: 0.2594552666414529
  rhythmicContrast: 0.9695850831922144
purpose: []
