name: 'Where, What?'
favicon: null
layout_spectrum: 0.16113645350560546
typography_spectrum: 0.43726812209933996
title: Contact
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2f0fb'
    - '#c7c1c1'
    - '#0d140d'
    - '#687240'
    - '#e04334'
  brandStrength: 0.625
  lightness: 0.6280691341962665
  saturation: 0.2594552666414529
  rhythmicContrast: 0.9695850831922144
purpose: []
