name: 'Where, What?'
favicon: null
layout_spectrum: 0.16113645350560546
typography_spectrum: 0.43726812209933996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7674754003528506
  lightness: 0.6280691341962665
  saturation: 0.2594552666414529
  rhythmicContrast: 0.9695850831922144
purpose: []
